name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn -q -DskipTests package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ManaFloorExpansion
          path: target/*.jar
